import type { Metadata } from "next";
import { Inter } from "next/font/google";
<<<<<<< HEAD

import "./globals.css";
import { ThemeProvider } from "./provider";
=======
import "./globals.css";
>>>>>>> 2a0d10b2a874ec7777a7cb479dc8ded143410c0a

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Adrian's Portfolio",
  description: "Modern & Minimal JS Mastery Portfolio",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 2a0d10b2a874ec7777a7cb479dc8ded143410c0a
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/jsm-logo.png" sizes="any" />
      </head>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
=======
    <html lang="en">
      <body className={inter.className}>{children}</body>
>>>>>>> 2a0d10b2a874ec7777a7cb479dc8ded143410c0a
    </html>
  );
}
